apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-app
spec:
  selector:
    matchLabels:
      app: currency-exchange-app
  replicas: 2
  template:
    metadata:
      labels:
        app: currency-exchange-app
    spec:
      containers:
        - name: "currency-exchange-service-sha256-1"
          image: "asia.gcr.io/kube-go-exp/currency-exchange-service@sha256:ee426b385ac46ab1ec19034f62a288c7c4fc7f892960c5f7f736969d5cbdc284"
          ports:
            - containerPort: 8000
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP