spring:
  profiles:
    active: "dev"
---
spring:
  application:
    name: currency-exchange-service
currencyExchange:
  appId: 76d9797902004813a592f6b2402590a9
  connectionTimeout: 30000
  requestTimeout: 30000
  socketTimeout: 60000
  maxTotalConnections: 50
  idleConnectionWaitTime: 30
server:
  port: 8000
feign:
  hystrix:
    enabled: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://ec2-18-223-159-199.us-east-2.compute.amazonaws.com:8761/eureka/
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
---
spring:
  profiles: test

---
spring:
  application:
    name: currency-exchange-service
currencyExchange:
  appId: 76d9797902004813a592f6b2402590a9
  connectionTimeout: 30000
  requestTimeout: 30000
  socketTimeout: 60000
  maxTotalConnections: 50
  idleConnectionWaitTime: 30
server:
  port: 8000