spring:
  profiles:
    active: "dev"
---
spring:
  profiles: dev
  application:
    name: currency-exchange-service
server:
  port: 8000
feign:
  hystrix:
    enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://ec2-18-223-159-199.us-east-2.compute.amazonaws.com:8761/eureka/
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost